<!DOCTYPE html>
<html lang="en"><head>
<script src="18-putting-it-together_files/libs/quarto-html/tabby.min.js"></script>
<script src="18-putting-it-together_files/libs/quarto-html/popper.min.js"></script>
<script src="18-putting-it-together_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="18-putting-it-together_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="18-putting-it-together_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="18-putting-it-together_files/libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Dr.&nbsp;Sara Weston">
  <meta name="dcterms.date" content="2026-06-03">
  <title>Putting It All Together</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="18-putting-it-together_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="18-putting-it-together_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="18-putting-it-together_files/libs/revealjs/dist/theme/quarto-f74f6804abaaff7c7e6dac51130874be.css">
  <link href="18-putting-it-together_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="18-putting-it-together_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="18-putting-it-together_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="18-putting-it-together_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="18-putting-it-together_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="18-putting-it-together_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link rel="stylesheet" href="toc-nav.css">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Putting It All Together</h1>
  <p class="subtitle">PSY 410: Data Science for Psychology</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Sara Weston 
</div>
</div>
</div>

  <p class="date">2026-06-03</p>
</section>

<section>
<section id="looking-back" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Looking back</h1>
<aside class="notes">
<p>This is the last class session. The tone should feel celebratory and reflective, not rushed. Final project videos are due during finals week, so today is about closing the loop. Start with a warm opening – acknowledge that it’s the end, and that you’re proud of how far they’ve come. The first ~10 minutes are about reflection before moving into the live demo.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-data-science-workflow" class="slide level2">
<h2>The data science workflow</h2>

<img data-src="https://r4ds.hadley.nz/diagrams/data-science/whole-game.png" style="width:80.0%" class="r-stretch quarto-figure-center"><p class="caption">R4DS data science workflow diagram showing the cycle: Import, Tidy, Transform, Visualize, Model, Communicate</p><div class="fragment">
<p>Ten weeks ago, you couldn’t do any of this. Now you can do all of it.</p>
<aside class="notes">
<p>Let this diagram sit for a moment. Ask students to name which sessions covered which parts of the cycle. Import (Session 6), Tidy (Session 5), Transform (Sessions 3-4), Visualize (Sessions 2, 8-9), Model (Session 17), Communicate (Sessions 7, 16). The point is that they’ve covered the entire workflow. This is the same R4DS diagram from the textbook – it should feel familiar.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="live-demonstration" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Live demonstration</h1>

</section>
<section id="a-real-analysis-start-to-finish" class="slide level2">
<h2>A real analysis: Start to finish</h2>
<p>Let’s analyze a <strong>real</strong> dataset together — the <a href="https://gss.norc.org/">General Social Survey</a>, included in <code>forcats</code> as <code>gss_cat</code>.</p>
<p><strong>Research question:</strong> Does age predict daily TV viewing among Americans — and does it differ by political party?</p>
<div class="fragment">
<p>I’ll demonstrate the full workflow:</p>
<ol type="1">
<li>Import and explore a real dataset</li>
<li>Clean and recode categories</li>
<li>Look at distributions (univariate &amp; by group)</li>
<li>Quantify the relationship (correlation + regression)</li>
<li>Reshape with pivots and joins</li>
<li>Build a Quarto report</li>
</ol>
<aside class="notes">
<p>This live demo is the heart of the lecture (~25-30 minutes). The dataset is real, public, and built into tidyverse – no download, no install. The research question is deliberately ordinary: it’s the kind of question a psych undergrad could answer for a class paper. As you walk through, name the session each step came from – this is the explicit “putting it all together” payoff. If time allows, live-code in RStudio alongside the slides.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-dataset" class="slide level2">
<h2>The dataset</h2>
<p><code>gss_cat</code> is a sample of the General Social Survey (NORC at the University of Chicago), one of the longest-running social surveys in the US.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_cat</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21,483 × 9
    year marital         age race  rincome        partyid    relig denom tvhours
   &lt;int&gt; &lt;fct&gt;         &lt;int&gt; &lt;fct&gt; &lt;fct&gt;          &lt;fct&gt;      &lt;fct&gt; &lt;fct&gt;   &lt;int&gt;
 1  2000 Never married    26 White $8000 to 9999  Ind,near … Prot… Sout…      12
 2  2000 Divorced         48 White $8000 to 9999  Not str r… Prot… Bapt…      NA
 3  2000 Widowed          67 White Not applicable Independe… Prot… No d…       2
 4  2000 Never married    39 White Not applicable Ind,near … Orth… Not …       4
 5  2000 Divorced         25 White Not applicable Not str d… None  Not …       1
 6  2000 Married          25 White $20000 - 24999 Strong de… Prot… Sout…      NA
 7  2000 Never married    36 White $25000 or more Not str r… Chri… Not …       3
 8  2000 Divorced         44 White $7000 to 7999  Ind,near … Prot… Luth…      NA
 9  2000 Married          44 White $25000 or more Not str d… Prot… Other       0
10  2000 Married          47 White $25000 or more Strong re… Prot… Sout…       3
# ℹ 21,473 more rows</code></pre>
</div>
</div>
<aside class="notes">
<p>The GSS has been running since 1972 and is a backbone dataset in sociology and political psychology. The version bundled with forcats covers 2000-2014 and 21,483 respondents. Highlight that this is <em>real data</em> – the kind their grad school mentors actually use.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-1-explore-the-data" class="slide level2">
<h2>Step 1: Explore the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(gss_cat)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 21,483
Columns: 9
$ year    &lt;int&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 20…
$ marital &lt;fct&gt; Never married, Divorced, Widowed, Never married, Divorced, Mar…
$ age     &lt;int&gt; 26, 48, 67, 39, 25, 25, 36, 44, 44, 47, 53, 52, 52, 51, 52, 40…
$ race    &lt;fct&gt; White, White, White, White, White, White, White, White, White,…
$ rincome &lt;fct&gt; $8000 to 9999, $8000 to 9999, Not applicable, Not applicable, …
$ partyid &lt;fct&gt; "Ind,near rep", "Not str republican", "Independent", "Ind,near…
$ relig   &lt;fct&gt; Protestant, Protestant, Protestant, Orthodox-christian, None, …
$ denom   &lt;fct&gt; "Southern baptist", "Baptist-dk which", "No denomination", "No…
$ tvhours &lt;int&gt; 12, NA, 2, 4, 1, NA, 3, NA, 0, 3, 2, NA, 1, NA, 1, 7, NA, 3, 3…</code></pre>
</div>
</div>
<aside class="notes">
<p>Emphasize that the first thing to do with any dataset is glimpse(). It tells you the dimensions, variable names, and types – everything you need to orient yourself.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-1-cont.-check-for-missing-data" class="slide level2">
<h2>Step 1 (cont.): Check for missing data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_cat <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.x))))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
   year marital   age  race rincome partyid relig denom tvhours
  &lt;int&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;   &lt;int&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;   &lt;int&gt;
1     0       0    76     0       0       0     0     0   10146</code></pre>
</div>
</div>
<aside class="notes">
<p>Ask: “What do you notice? Which variables have a lot of NAs? Which have none?” tvhours has the most because the question wasn’t asked every year. This connects directly back to Session 14 on missing data.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="whats-in-partyid" class="slide level2">
<h2>What’s in <code>partyid</code>?</h2>
<p>Before we recode, let’s see what’s actually there:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_cat <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(partyid)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   partyid                n
   &lt;fct&gt;              &lt;int&gt;
 1 No answer            154
 2 Don't know             1
 3 Other party          393
 4 Strong republican   2314
 5 Not str republican  3032
 6 Ind,near rep        1791
 7 Independent         4119
 8 Ind,near dem        2499
 9 Not str democrat    3690
10 Strong democrat     3490</code></pre>
</div>
</div>
<aside class="notes">
<p>Always check the levels of a categorical variable before recoding it. Students often assume the values they expect; the data has 10 levels including ‘No answer’, ‘Don’t know’, and ‘Other party’. Point out that ‘Ind,near rep’ and ‘Ind,near dem’ are leaners – we’ll group them with Independents in the next step. This habit (count() before case_when()) prevents the most common recoding bug: typos in the lookup strings silently producing NAs.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-2-clean-the-data" class="slide level2">
<h2>Step 2: Clean the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_clean <span class="ot">&lt;-</span> gss_cat <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(tvhours, age) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">party =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-5"><a href="" aria-hidden="true" tabindex="-1"></a>      partyid <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Strong republican"</span>, <span class="st">"Not str republican"</span>) <span class="sc">~</span> <span class="st">"Republican"</span>,</span>
<span id="cb9-6"><a href="" aria-hidden="true" tabindex="-1"></a>      partyid <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Strong democrat"</span>, <span class="st">"Not str democrat"</span>)     <span class="sc">~</span> <span class="st">"Democrat"</span>,</span>
<span id="cb9-7"><a href="" aria-hidden="true" tabindex="-1"></a>      partyid <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Ind,near rep"</span>, <span class="st">"Independent"</span>, <span class="st">"Ind,near dem"</span>) <span class="sc">~</span> <span class="st">"Independent"</span>,</span>
<span id="cb9-8"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb9-9"><a href="" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">party =</span> <span class="fu">factor</span>(party, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>, <span class="st">"Independent"</span>, <span class="st">"Republican"</span>))</span>
<span id="cb9-11"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-12"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(party)</span></code></pre></div>
</div>
<aside class="notes">
<p>Walk through each cleaning decision. “Why drop_na on tvhours and age?” Because we can’t analyze missing values. “Why collapse partyid into three categories?” Because the raw variable has 10 levels including ‘Don’t know’ and ‘No answer’ – too granular to plot. We’re treating ‘near rep’ and ‘near dem’ leaners as Independents for simplicity. Each of these decisions maps to a session: drop_na (Session 14), case_when (Session 4), factor levels (Session 12).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-3-descriptive-statistics" class="slide level2">
<h2>Step 3: Descriptive statistics</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_clean <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb10-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb10-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_age =</span> <span class="fu">mean</span>(age),</span>
<span id="cb10-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_tv =</span> <span class="fu">mean</span>(tvhours),</span>
<span id="cb10-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_tv =</span> <span class="fu">sd</span>(tvhours)</span>
<span id="cb10-7"><a href="" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
      n mean_age mean_tv sd_tv
  &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 11026     47.2    2.98  2.57</code></pre>
</div>
</div>
</section>
<section id="step-3-cont.-group-sizes" class="slide level2">
<h2>Step 3 (cont.): Group sizes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_clean <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(party)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  party           n
  &lt;fct&gt;       &lt;int&gt;
1 Democrat     3832
2 Independent  4461
3 Republican   2733</code></pre>
</div>
</div>
</section>
<section id="step-4-how-much-tv-do-people-watch" class="slide level2">
<h2>Step 4: How much TV do people watch?</h2>
<p>Start with <strong>univariate EDA</strong> — one variable at a time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gss_clean, <span class="fu">aes</span>(<span class="at">x =</span> tvhours)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Most respondents watch 1-3 hours per day"</span>,</span>
<span id="cb14-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"But the tail stretches to 24 hours"</span>,</span>
<span id="cb14-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Hours of TV per day"</span>,</span>
<span id="cb14-7"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of respondents"</span></span>
<span id="cb14-8"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-9"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
</div>

<aside class="notes">
<p>This is Session 10 territory – look at the shape of one variable before anything else. The distribution is right-skewed with a peak at 2 hours and a tail of heavy viewers. Ask: “What kinds of people might be in that tail?” The skew matters because mean &gt; median when data is skewed – a chance to remind them why we often prefer the median for skewed data.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-4-how-much-tv-do-people-watch-output" class="slide level2 output-location-slide"><h2>Step 4: How much TV do people watch?</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="18-putting-it-together_files/figure-revealjs/unnamed-chunk-9-1.png" alt="Histogram of daily TV hours peaking at 2 hours per day with a long right tail." width="960"></p>
</figure>
</div>
</div>
</div></section><section id="step-4-cont.-does-it-differ-by-party" class="slide level2">
<h2>Step 4 (cont.): Does it differ by party?</h2>
<p>Now <strong>bivariate EDA</strong> — compare distributions across groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gss_clean, <span class="fu">aes</span>(<span class="at">x =</span> party, <span class="at">y =</span> tvhours, <span class="at">fill =</span> party)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb15-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Democrat"</span>    <span class="ot">=</span> <span class="st">"#3498db"</span>,</span>
<span id="cb15-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Independent"</span> <span class="ot">=</span> <span class="st">"#7f8c8d"</span>,</span>
<span id="cb15-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Republican"</span>  <span class="ot">=</span> <span class="st">"#e74c3c"</span></span>
<span id="cb15-7"><a href="" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb15-8"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"TV viewing distributions look similar across parties"</span>,</span>
<span id="cb15-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb15-11"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Hours of TV per day"</span></span>
<span id="cb15-12"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-13"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-14"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div>
</div>

<aside class="notes">
<p>Session 11 – covariation between a categorical and a continuous variable. The boxplot is the workhorse for “does this group matter for that number?” Point out the medians (the bold line inside the box), the IQR (box height), and the outliers (dots). Quick check: medians look similar across parties, so party probably won’t be a big driver in our model.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-4-cont.-does-it-differ-by-party-output" class="slide level2 output-location-slide"><h2>Step 4 (cont.): Does it differ by party?</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="18-putting-it-together_files/figure-revealjs/unnamed-chunk-10-1.png" alt="Side-by-side boxplots of daily TV hours for Democrats, Independents, and Republicans showing similar medians and spreads." width="960"></p>
</figure>
</div>
</div>
</div></section><section id="step-5-initial-visualization" class="slide level2">
<h2>Step 5: Initial visualization</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gss_clean, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> tvhours)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">height =</span> <span class="fl">0.3</span>, <span class="at">width =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Older Americans report more daily TV viewing"</span>,</span>
<span id="cb16-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"General Social Survey, 2000-2014"</span>,</span>
<span id="cb16-7"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb16-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Hours of TV per day"</span></span>
<span id="cb16-9"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-10"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
</div>

</section>
<section id="step-5-initial-visualization-output" class="slide level2 output-location-slide"><h2>Step 5: Initial visualization</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="18-putting-it-together_files/figure-revealjs/unnamed-chunk-11-1.png" alt="Scatterplot with a linear trend line showing that older Americans report more daily TV viewing in the General Social Survey." width="960"></p>
</figure>
</div>
</div>
</div></section><section id="step-6-compute-correlation" class="slide level2">
<h2>Step 6: Compute correlation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="" aria-hidden="true" tabindex="-1"></a>cor_value <span class="ot">&lt;-</span> <span class="fu">cor</span>(gss_clean<span class="sc">$</span>age, gss_clean<span class="sc">$</span>tvhours)</span>
<span id="cb17-2"><a href="" aria-hidden="true" tabindex="-1"></a>cor_value</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1424147</code></pre>
</div>
</div>
<div class="fragment">
<p><strong>Finding:</strong> A small but reliable positive correlation (r = 0.14).</p>
<aside class="notes">
<p>This is a callback to Monday’s session. Ask students to interpret the correlation in plain language before you advance to the finding. “What does r ≈ 0.14 mean in real terms?” Students who were in Session 17 should be able to answer this. Worth noting: with N this large, even tiny correlations are ‘statistically significant’ – a great chance to remind them that effect size matters more than p-values.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="step-7-run-a-regression" class="slide level2">
<h2>Step 7: Run a regression</h2>
<p>A correlation gives one number. A regression gives a <strong>slope</strong> — how much does TV viewing change per year of age?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="" aria-hidden="true" tabindex="-1"></a>tv_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(tvhours <span class="sc">~</span> age <span class="sc">+</span> party, <span class="at">data =</span> gss_clean)</span>
<span id="cb19-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb19-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(tv_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term             estimate std.error statistic   p.value
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        2.24     0.0795      28.2  5.22e-169
2 age                0.0212   0.00140     15.2  2.17e- 51
3 partyIndependent  -0.262    0.0562      -4.67 2.99e-  6
4 partyRepublican   -0.618    0.0635      -9.73 2.69e- 22</code></pre>
</div>
</div>
<aside class="notes">
<p>Direct callback to Session 17. The lm() formula syntax (<code>y ~ x1 + x2</code>) is the foundation for almost all R modeling – t-tests, ANOVA, mixed models, even Bayesian models use the same notation. broom::tidy() turns the messy summary() output into a tidy tibble we can pipe and plot. Walk through the estimate column: the age slope tells us about how many additional minutes of TV per year of age.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-7-cont.-how-well-does-it-fit" class="slide level2">
<h2>Step 7 (cont.): How well does it fit?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(tv_model) <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(r.squared, adj.r.squared, sigma, nobs)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  r.squared adj.r.squared sigma  nobs
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1    0.0286        0.0284  2.54 11026</code></pre>
</div>
</div>
<div class="fragment">
<p>R² is tiny — age and party explain only a small slice of TV viewing. The story isn’t <em>wrong</em>, it just isn’t the whole story.</p>
<aside class="notes">
<p><code>glance()</code> gives one-row model summaries; <code>tidy()</code> gives one row per coefficient. Together they’re the broom workflow. The small R² is the right teaching moment: “statistically significant” ≠ “explains a lot.” Pair this with the earlier note about effect size. This also makes the case for multivariate models in PSY 420 – we’re not capturing the variables that really matter (income, education, screen-time substitution, etc.).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="step-8-does-the-pattern-differ-by-party" class="slide level2">
<h2>Step 8: Does the pattern differ by party?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gss_clean, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> tvhours, <span class="at">color =</span> party)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb23-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Democrat"</span>    <span class="ot">=</span> <span class="st">"#3498db"</span>,</span>
<span id="cb23-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Independent"</span> <span class="ot">=</span> <span class="st">"#7f8c8d"</span>,</span>
<span id="cb23-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Republican"</span>  <span class="ot">=</span> <span class="st">"#e74c3c"</span></span>
<span id="cb23-7"><a href="" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb23-8"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Same pattern across the political spectrum"</span>,</span>
<span id="cb23-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb23-11"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Hours of TV per day"</span>,</span>
<span id="cb23-12"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Party"</span></span>
<span id="cb23-13"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-14"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-15"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code></pre></div>
</div>

</section>
<section id="step-8-does-the-pattern-differ-by-party-output" class="slide level2 output-location-slide"><h2>Step 8: Does the pattern differ by party?</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="18-putting-it-together_files/figure-revealjs/unnamed-chunk-15-1.png" alt="Scatterplot with separate colored trend lines for Democrats, Independents, and Republicans, showing a similar positive age-TV slope for all three groups." width="960"></p>
</figure>
</div>
</div>
</div></section><section id="step-9-tv-viewing-categories" class="slide level2">
<h2>Step 9: TV viewing categories</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_clean <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">tv_category =</span> <span class="fu">case_when</span>(</span>
<span id="cb24-4"><a href="" aria-hidden="true" tabindex="-1"></a>      tvhours <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"None"</span>,</span>
<span id="cb24-5"><a href="" aria-hidden="true" tabindex="-1"></a>      tvhours <span class="sc">&lt;=</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Light (1-2 hr)"</span>,</span>
<span id="cb24-6"><a href="" aria-hidden="true" tabindex="-1"></a>      tvhours <span class="sc">&lt;=</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Moderate (3-4 hr)"</span>,</span>
<span id="cb24-7"><a href="" aria-hidden="true" tabindex="-1"></a>      tvhours <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Heavy (5+ hr)"</span></span>
<span id="cb24-8"><a href="" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb24-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">tv_category =</span> <span class="fu">factor</span>(tv_category,</span>
<span id="cb24-10"><a href="" aria-hidden="true" tabindex="-1"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"Light (1-2 hr)"</span>,</span>
<span id="cb24-11"><a href="" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Moderate (3-4 hr)"</span>, <span class="st">"Heavy (5+ hr)"</span>))</span>
<span id="cb24-12"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb24-13"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(tv_category) <span class="sc">|&gt;</span></span>
<span id="cb24-14"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> <span class="fu">fct_rev</span>(tv_category), <span class="at">fill =</span> tv_category)) <span class="sc">+</span></span>
<span id="cb24-15"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb24-16"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb24-17"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"None"</span>              <span class="ot">=</span> <span class="st">"#2ecc71"</span>,</span>
<span id="cb24-18"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Light (1-2 hr)"</span>    <span class="ot">=</span> <span class="st">"#f39c12"</span>,</span>
<span id="cb24-19"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Moderate (3-4 hr)"</span> <span class="ot">=</span> <span class="st">"#e67e22"</span>,</span>
<span id="cb24-20"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Heavy (5+ hr)"</span>     <span class="ot">=</span> <span class="st">"#e74c3c"</span></span>
<span id="cb24-21"><a href="" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb24-22"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-23"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Most Americans watch 1-4 hours of TV per day"</span>,</span>
<span id="cb24-24"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of respondents"</span>,</span>
<span id="cb24-25"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb24-26"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-27"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-28"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div>
</div>

</section>
<section id="step-9-tv-viewing-categories-output" class="slide level2 output-location-slide"><h2>Step 9: TV viewing categories</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="18-putting-it-together_files/figure-revealjs/unnamed-chunk-16-1.png" alt="Horizontal bar chart of TV viewing categories showing most Americans watch 1-4 hours per day, with smaller groups at None and Heavy." width="960"></p>
</figure>
</div>
</div>
</div></section><section id="step-10-has-tv-viewing-changed-over-time" class="slide level2">
<h2>Step 10: Has TV viewing changed over time?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_clean <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_tv =</span> <span class="fu">mean</span>(tvhours), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> mean_tv)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Mean daily TV viewing across GSS years"</span>,</span>
<span id="cb25-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Survey year"</span>,</span>
<span id="cb25-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean hours of TV per day"</span></span>
<span id="cb25-11"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-12"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
</div>

<aside class="notes">
<p>This is a grouped summary feeding straight into a plot – a pattern they’ll use constantly. Note how <code>group_by() |&gt; summarize()</code> collapses 21,000 rows into 8. The line plot is intuitive for time series. Ask: “What might explain a downward drift in TV hours over this period?” (Streaming, YouTube, social media displacing traditional TV.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-10-has-tv-viewing-changed-over-time-output" class="slide level2 output-location-slide"><h2>Step 10: Has TV viewing changed over time?</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="18-putting-it-together_files/figure-revealjs/unnamed-chunk-17-1.png" alt="Line plot of mean daily TV hours from 2000 to 2014, drifting slightly downward across the period." width="960"></p>
</figure>
</div>
</div>
</div></section><section id="step-11-add-political-context-with-a-join" class="slide level2">
<h2>Step 11: Add political context with a join</h2>
<p>What if we want to label each year by who was president? We need a second table, then a <strong>join</strong> (Session 15).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="" aria-hidden="true" tabindex="-1"></a>president_lookup <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb26-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>year, <span class="sc">~</span>president,</span>
<span id="cb26-3"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2000</span>, <span class="st">"Clinton"</span>,</span>
<span id="cb26-4"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2002</span>, <span class="st">"G.W. Bush"</span>,</span>
<span id="cb26-5"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2004</span>, <span class="st">"G.W. Bush"</span>,</span>
<span id="cb26-6"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2006</span>, <span class="st">"G.W. Bush"</span>,</span>
<span id="cb26-7"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2008</span>, <span class="st">"G.W. Bush"</span>,</span>
<span id="cb26-8"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2010</span>, <span class="st">"Obama"</span>,</span>
<span id="cb26-9"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2012</span>, <span class="st">"Obama"</span>,</span>
<span id="cb26-10"><a href="" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2014</span>, <span class="st">"Obama"</span></span>
<span id="cb26-11"><a href="" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-12"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="" aria-hidden="true" tabindex="-1"></a>president_lookup</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
   year president
  &lt;dbl&gt; &lt;chr&gt;    
1  2000 Clinton  
2  2002 G.W. Bush
3  2004 G.W. Bush
4  2006 G.W. Bush
5  2008 G.W. Bush
6  2010 Obama    
7  2012 Obama    
8  2014 Obama    </code></pre>
</div>
</div>
<aside class="notes">
<p><code>tribble()</code> is the row-by-row tibble constructor – nice for small lookups like this. The next slide does the actual join. Frame the join as “add columns from another table by matching on a key.” The key here is <code>year</code>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-11-cont.-the-join" class="slide level2">
<h2>Step 11 (cont.): The join</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="" aria-hidden="true" tabindex="-1"></a>gss_with_president <span class="ot">&lt;-</span> gss_clean <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(president_lookup, <span class="at">by =</span> <span class="st">"year"</span>)</span>
<span id="cb28-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="" aria-hidden="true" tabindex="-1"></a>gss_with_president <span class="sc">|&gt;</span></span>
<span id="cb28-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(president) <span class="sc">|&gt;</span></span>
<span id="cb28-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb28-7"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb28-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_tv =</span> <span class="fu">mean</span>(tvhours),</span>
<span id="cb28-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb28-10"><a href="" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb28-11"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_tv))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  president     n mean_tv
  &lt;chr&gt;     &lt;int&gt;   &lt;dbl&gt;
1 Obama      4245    3.02
2 Clinton    1799    2.99
3 G.W. Bush  4982    2.95</code></pre>
</div>
</div>
<div class="fragment">
<p>Tiny differences — but the <em>technique</em> is what counts. Joins let you bring in any external data (codebooks, demographics, neighborhood stats).</p>
<aside class="notes">
<p>Big caveat: this is correlation, not causation. TV viewing didn’t change because the president changed. The point is the <em>mechanic</em> of the join, plus <code>arrange(desc(...))</code> to sort. Real psych use: joining survey responses with demographics, or wave 1 with wave 2 of a longitudinal study.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="step-12-summary-table-by-party" class="slide level2">
<h2>Step 12: Summary table by party</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> gss_clean <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(party) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb30-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">N        =</span> <span class="fu">n</span>(),</span>
<span id="cb30-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean_Age =</span> <span class="fu">mean</span>(age),</span>
<span id="cb30-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean_TV  =</span> <span class="fu">mean</span>(tvhours),</span>
<span id="cb30-7"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD_TV    =</span> <span class="fu">sd</span>(tvhours),</span>
<span id="cb30-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups  =</span> <span class="st">"drop"</span></span>
<span id="cb30-9"><a href="" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb30-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(summary_table, <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb30-12"><a href="" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Party"</span>, <span class="st">"N"</span>, <span class="st">"M Age"</span>, <span class="st">"M TV"</span>, <span class="st">"SD TV"</span>))</span></code></pre></div>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Party</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">M Age</th>
<th style="text-align: right;">M TV</th>
<th style="text-align: right;">SD TV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Democrat</td>
<td style="text-align: right;">3832</td>
<td style="text-align: right;">48.7</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">2.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Independent</td>
<td style="text-align: right;">4461</td>
<td style="text-align: right;">44.8</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">2.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Republican</td>
<td style="text-align: right;">2733</td>
<td style="text-align: right;">49.2</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">2.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="step-13-write-it-up-in-quarto" class="slide level2">
<h2>Step 13: Write it up in Quarto</h2>
<div class="sourceCode" id="cb31"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb31-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results</span></span>
<span id="cb31-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="" aria-hidden="true" tabindex="-1"></a>We analyzed data from <span class="in">`r nrow(gss_clean)`</span> respondents in</span>
<span id="cb31-4"><a href="" aria-hidden="true" tabindex="-1"></a>the General Social Survey (2000-2014), with a mean age of</span>
<span id="cb31-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="in">`r round(mean(gss_clean$age), 1)`</span> years. Respondents reported</span>
<span id="cb31-6"><a href="" aria-hidden="true" tabindex="-1"></a>watching <span class="in">`r round(mean(gss_clean$tvhours), 1)`</span> hours of TV per</span>
<span id="cb31-7"><a href="" aria-hidden="true" tabindex="-1"></a>day on average (SD = <span class="in">`r round(sd(gss_clean$tvhours), 1)`</span>).</span>
<span id="cb31-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="" aria-hidden="true" tabindex="-1"></a>Age was positively correlated with daily TV viewing</span>
<span id="cb31-10"><a href="" aria-hidden="true" tabindex="-1"></a>(r = <span class="in">`r round(cor_value, 2)`</span>), such that older respondents</span>
<span id="cb31-11"><a href="" aria-hidden="true" tabindex="-1"></a>tended to report more hours of TV.</span></code></pre></div>
<aside class="notes">
<p>The inline R expressions (the backtick-r bits) are the magic. They evaluate at render time, so the numbers in the prose are pulled live from the data. No hand-typed numbers; no copy-paste from console output. If the data changes, the writeup updates automatically. Next slide shows what this renders to.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-13-cont.-what-it-renders-to" class="slide level2">
<h2>Step 13 (cont.): What it renders to</h2>
<h3 id="results">Results</h3>
<p>We analyzed data from 11026 respondents in the General Social Survey (2000-2014), with a mean age of 47.2 years. Respondents reported watching 3 hours of TV per day on average (SD = 2.6).</p>
<p>Age was positively correlated with daily TV viewing (r = 0.14), such that older respondents tended to report more hours of TV. The relationship was similar across Democrats, Independents, and Republicans.</p>

<img data-src="18-putting-it-together_files/figure-revealjs/unnamed-chunk-22-1.png" alt="Small scatterplot of age and daily TV hours with a steelblue linear trend line." width="672" class="r-stretch"><aside class="notes">
<p>This is the same prose from the previous slide, but rendered. Point at the numbers and say “every one of these came from the data via inline R.” If you change the dataset (add rows, drop a year), every number updates on re-render. This is what ‘reproducible’ actually buys you.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-this-demonstrates" class="slide level2">
<h2>What this demonstrates</h2>
<ul>
<li>✅ <strong>Explore &amp; clean</strong> — <code>glimpse</code>, <code>count</code>, <code>case_when</code>, <code>drop_na</code>, <code>factor</code></li>
<li>✅ <strong>Univariate &amp; bivariate EDA</strong> — <code>geom_histogram</code>, <code>geom_boxplot</code></li>
<li>✅ <strong>Quantify</strong> — <code>cor</code>, <code>lm</code>, <code>broom::tidy</code>, <code>broom::glance</code></li>
<li>✅ <strong>Group &amp; reshape</strong> — <code>group_by</code>, <code>summarize</code>, <code>tribble</code>, <code>left_join</code>, <code>arrange</code></li>
<li>✅ <strong>Visualize</strong> — scatter, line, bar, box; color, scale, theme, labs</li>
<li>✅ <strong>Communicate</strong> — <code>kable</code> tables + inline R in Quarto</li>
</ul>
<div class="fragment">
<p><strong>One pipeline. Sixteen sessions of skills.</strong></p>
<aside class="notes">
<p>This is the payoff slide. Read each line and name the session it came from. The closing line should land – they’ve genuinely used skills from nearly every session in one connected analysis. Then transition: “But what happens when things go wrong? Because they will, even for experienced programmers.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="when-things-break" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>When things break</h1>

</section>
<section id="the-6-errors-youll-see-most-often-12" class="slide level2">
<h2>The 6 errors you’ll see most often (1/2)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 55%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Error</th>
<th>What it means</th>
<th>Fix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>object 'x' not found</code></td>
<td>Typo, wrong capitalization, or object not created yet</td>
<td>Check spelling; run the code that creates it</td>
</tr>
<tr class="even">
<td><code>could not find function</code></td>
<td>Typo in function name or package not loaded</td>
<td>Check spelling; run <code>library()</code></td>
</tr>
<tr class="odd">
<td><code>unexpected symbol</code></td>
<td>Missing <code>|&gt;</code>, <code>+</code>, comma, or parenthesis</td>
<td>Check the line <em>before</em> the error</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Ask students: “Which of these have you gotten this quarter?” Hands will go up for all three. The most common is “object not found” (usually a capitalization issue or forgetting to run an earlier chunk). The “unexpected symbol” error is the trickiest because the actual problem is on the line <em>before</em> the error – emphasize checking the previous line.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-6-errors-youll-see-most-often-22" class="slide level2">
<h2>The 6 errors you’ll see most often (2/2)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 55%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Error</th>
<th>What it means</th>
<th>Fix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>non-numeric argument</code></td>
<td>Math on text — variable is character, not numeric</td>
<td>Check type with <code>class()</code> or <code>glimpse()</code></td>
</tr>
<tr class="even">
<td><code>did you mean '=='?</code></td>
<td>Used <code>=</code> (assignment) instead of <code>==</code> (comparison) in <code>filter()</code></td>
<td>Change <code>=</code> to <code>==</code></td>
</tr>
<tr class="odd">
<td>ggplot <code>+</code> error</td>
<td>Missing <code>+</code> between ggplot layers</td>
<td>Every line except the last needs <code>+</code></td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>The bottom three are operator and syntax errors. The “did you mean ==” error is friendly – R is literally telling you the fix. The ggplot + error is a classic Session 2 issue that still trips students up; remind them ggplot uses + between layers, not |&gt;.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-5-step-debugging-strategy" class="slide level2">
<h2>A 5-step debugging strategy</h2>
<ol type="1">
<li><strong>Read the error message</strong> — actually read it. It tells you <em>where</em> and <em>what</em>.</li>
</ol>
<div class="fragment">
<ol start="2" type="1">
<li><strong>Check the basics</strong> — package loaded? Object created? Spelling correct?</li>
</ol>
</div>
<div class="fragment">
<ol start="3" type="1">
<li><strong>Run line by line</strong> — pipe chains: run from the top, adding one line at a time. Which line breaks?</li>
</ol>
</div>
<div class="fragment">
<ol start="4" type="1">
<li><strong>Simplify</strong> — make a tiny test dataset (<code>tibble(x = 1:3)</code>) and try the same operation.</li>
</ol>
</div>
<div class="fragment">
<ol start="5" type="1">
<li><strong>Google it</strong> — include “R”, the package name, and the exact error message.</li>
</ol>
<aside class="notes">
<p>Step 3 (“run line by line”) is the most underused debugging technique among beginners. Demo it quickly: take a piped chain, highlight just the first line and run it, then add the next line, and so on. The line where it breaks is where the bug is. This is the single most useful debugging habit they can develop. Steps 1-3 solve ~90% of bugs.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="when-you-ask-for-help-make-a-reprex" class="slide level2">
<h2>When you ask for help: make a reprex</h2>
<p><strong>Reprex</strong> = <strong>repr</strong>oducible <strong>ex</strong>ample — the smallest code that recreates your error.</p>
<div class="fragment">
<p><strong>Bad:</strong> “My code doesn’t work. Help!”</p>
</div>
<div class="fragment">
<p><strong>Good:</strong></p>
<blockquote>
<p>“I’m trying to filter my data but getting ‘object not found’:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb32-2"><a href="" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">y =</span> <span class="fu">c</span>(<span class="st">"a"</span>, <span class="st">"b"</span>, <span class="st">"c"</span>))</span>
<span id="cb32-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(data, x <span class="sc">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb32-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Error: object 'data' not found</span></span></code></pre></div>
<p>I expected rows where x &gt; 1.”</p>
</blockquote>
</div>
<div class="fragment">
<p><strong>Tip:</strong> Use <code>dput()</code> to share a small slice of your real data so others can recreate it exactly.</p>
<aside class="notes">
<p>The reprex concept is a life skill for programming. Emphasize the contrast between the “bad” and “good” examples. The good example includes: the library call, a minimal dataset, the code that fails, and the expected vs.&nbsp;actual result. Even if students never post on Stack Overflow, learning to create a reprex forces them to isolate the problem – which often helps them solve it themselves.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="where-to-get-help-after-this-course" class="slide level2">
<h2>Where to get help after this course</h2>
<ul>
<li><a href="https://stackoverflow.com">Stack Overflow</a> — searchable Q&amp;A (look for green checkmark ✅)</li>
<li><a href="https://community.rstudio.com">Posit Community</a> — friendly R forum</li>
<li><a href="https://r4ds.io/join">R4DS Slack</a> — real-time chat</li>
<li><a href="https://rladies.org">R-Ladies</a> — supportive community with local chapters</li>
</ul>
<div class="fragment">
<p><strong>Before posting:</strong> search first, be specific, show what you tried, and include a reprex.</p>
</div>
</section></section>
<section>
<section id="pair-coding-break" class="title-slide slide level1 center" data-background-color="#e67e22">
<h1>Pair coding break</h1>

</section>
<section id="your-turn-debug-this-code" class="slide level2">
<h2>Your turn: Debug this code</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>There are at least 4 bugs. Read each line carefully and check: names, operators, punctuation.</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb33-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="" aria-hidden="true" tabindex="-1"></a>Study_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb33-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb33-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">Score =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">14</span>),</span>
<span id="cb33-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">Group =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"A"</span>)</span>
<span id="cb33-7"><a href="" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="" aria-hidden="true" tabindex="-1"></a>study_data <span class="sc">|&gt;</span></span>
<span id="cb33-10"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="at">Group =</span> <span class="st">"A"</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-11"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb33-12"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_score =</span> <span class="fu">mean</span>(score)</span>
<span id="cb33-13"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_score =</span> <span class="fu">sd</span>(score)</span>
<span id="cb33-14"><a href="" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<p><strong>Time: 10 minutes</strong></p>
<aside class="notes">
<p>This is the final pair coding exercise of the course – 10 minutes. There are 4 bugs: (1) Study_data vs study_data capitalization mismatch, (2) single = instead of == in filter, (3) Score vs score capitalization mismatch, (4) missing comma between summarize arguments. Circulate and see how quickly pairs find all four. Bug 1 and 3 (capitalization) are the trickiest because the error message just says “object not found.” Bug 2 gives a helpful error (“Did you mean ==?”). Bug 4 gives “unexpected symbol.” This exercise reinforces the debugging strategy from the previous slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-we-move-on" class="slide level2">
<h2>Before we move on</h2>
<p>📤 <strong><a href="https://canvas.uoregon.edu/courses/287793/pages/pair-coding-check-ins">Submit your code on Canvas</a></strong> for participation credit. Paste what you have — it doesn’t need to work perfectly.</p>
</section></section>
<section>
<section id="where-to-go-from-here" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Where to go from here</h1>

</section>
<section id="you-have-the-foundation" class="slide level2">
<h2>You have the foundation</h2>
<aside class="notes">
<p>Transition to the forward-looking section (~10 minutes for the “Where to go from here” block). The goal is to show students that this course was the on-ramp, not the destination. Each of the next slides shows one possible direction. Don’t spend too long on any one – just plant seeds. Students who are interested will follow up on their own.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<p>This course covered <strong>data wrangling and visualization</strong> — the foundation of data science.</p>
<div class="fragment">
<p>What’s next?</p>
<ul>
<li><strong>Statistics in R</strong> — inference, hypothesis testing</li>
<li><strong>Writing functions</strong> — automate repetitive work</li>
<li><strong>Version control</strong> — Git and GitHub</li>
<li><strong>Interactive tools</strong> — Shiny dashboards</li>
<li><strong>The wider R ecosystem</strong> — tidymodels, tidytext, and more</li>
</ul>
</div>
</section>
<section id="statistics-in-r" class="slide level2">
<h2>Statistics in R</h2>
<p>You can now learn inferential statistics:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test (compare two groups)</span></span>
<span id="cb34-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(tvhours <span class="sc">~</span> <span class="fu">I</span>(party <span class="sc">==</span> <span class="st">"Republican"</span>), <span class="at">data =</span> gss_clean)</span>
<span id="cb34-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA (compare multiple groups)</span></span>
<span id="cb34-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(tvhours <span class="sc">~</span> party, <span class="at">data =</span> gss_clean)</span>
<span id="cb34-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression</span></span>
<span id="cb34-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(tvhours <span class="sc">~</span> age <span class="sc">+</span> party, <span class="at">data =</span> gss_clean)</span></code></pre></div>
</div>
<div class="fragment">
<p><strong>Courses to consider:</strong></p>
<ul>
<li>PSY 420: Advanced Statistics</li>
<li>STAT 510: Applied Regression</li>
<li>Online: <a href="https://learningstatisticswithr.com/">Learning Statistics with R</a></li>
</ul>
<aside class="notes">
<p>This is the most natural next step for psych majors. Emphasize that the code syntax is nearly identical to what they learned in Session 17 – t.test, aov, and lm all follow the same formula syntax. If students are taking PSY 420 or a stats course next, they’ll already know the R side.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="writing-functions" class="slide level2">
<h2>Writing functions</h2>
<p>Automate repetitive tasks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Instead of copying this code multiple times...</span></span>
<span id="cb35-2"><a href="" aria-hidden="true" tabindex="-1"></a>compute_scale_score <span class="ot">&lt;-</span> <span class="cf">function</span>(data, items) {</span>
<span id="cb35-3"><a href="" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rowwise</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">score =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">all_of</span>(items)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span>
<span id="cb35-7"><a href="" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Use it anywhere</span></span>
<span id="cb35-10"><a href="" aria-hidden="true" tabindex="-1"></a>phq9_scored <span class="ot">&lt;-</span> <span class="fu">compute_scale_score</span>(my_data, <span class="fu">c</span>(<span class="st">"phq1"</span>, <span class="st">"phq2"</span>, <span class="st">"phq3"</span>))</span></code></pre></div>
</div>
</section>
<section id="version-control-with-git" class="slide level2">
<h2>Version control with Git</h2>
<p>Track changes to your code over time:</p>
<ul>
<li><strong>Never lose work</strong> — full history of changes</li>
<li><strong>Collaborate easily</strong> — merge changes from multiple people</li>
<li><strong>Professional standard</strong> — expected in industry and academia</li>
</ul>
<div class="fragment">
<p><strong>Resources:</strong></p>
<ul>
<li><a href="https://happygitwithr.com/">Happy Git with R</a></li>
<li><a href="https://lab.github.com/">GitHub Learning Lab</a></li>
</ul>
</div>
</section>
<section id="interactive-visualizations-with-shiny" class="slide level2">
<h2>Interactive visualizations with Shiny</h2>
<p>Build web apps for your data — no HTML or JavaScript required:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(shiny)</span>
<span id="cb36-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="" aria-hidden="true" tabindex="-1"></a>ui <span class="ot">&lt;-</span> <span class="fu">fluidPage</span>(</span>
<span id="cb36-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">selectInput</span>(<span class="st">"party"</span>, <span class="st">"Choose party:"</span>,</span>
<span id="cb36-5"><a href="" aria-hidden="true" tabindex="-1"></a>              <span class="at">choices =</span> <span class="fu">c</span>(<span class="st">"Democrat"</span>, <span class="st">"Independent"</span>, <span class="st">"Republican"</span>)),</span>
<span id="cb36-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plotOutput</span>(<span class="st">"plot"</span>)</span>
<span id="cb36-7"><a href="" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="" aria-hidden="true" tabindex="-1"></a>server <span class="ot">&lt;-</span> <span class="cf">function</span>(input, output) {</span>
<span id="cb36-10"><a href="" aria-hidden="true" tabindex="-1"></a>  output<span class="sc">$</span>plot <span class="ot">&lt;-</span> <span class="fu">renderPlot</span>({</span>
<span id="cb36-11"><a href="" aria-hidden="true" tabindex="-1"></a>    gss_clean <span class="sc">|&gt;</span></span>
<span id="cb36-12"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(party <span class="sc">==</span> input<span class="sc">$</span>party) <span class="sc">|&gt;</span></span>
<span id="cb36-13"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggplot</span>(<span class="fu">aes</span>(age, tvhours)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb36-14"><a href="" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb36-15"><a href="" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb36-16"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">shinyApp</span>(ui, server)</span></code></pre></div>
</div>
</section>
<section id="see-shiny-in-action" class="slide level2">
<h2>See Shiny in action</h2>
<iframe src="https://gallery.shinyapps.io/051-movie-explorer/" width="100%" height="500" frameborder="0">
</iframe>
<p>Posit’s classic <a href="https://shiny.posit.co/r/gallery/start-simple/movie-explorer/">Movie Explorer</a> — try the sliders and dropdowns.</p>
<aside class="notes">
<p>This is Posit’s canonical Shiny demo. Let students poke at it for 30-60 seconds. Point out the live filtering – every change updates the plot without reloading. The entire app is ~50 lines of R. After class, students can browse the full gallery at shiny.posit.co/r/gallery for more examples. If the iframe doesn’t load (network/firewall), open the link directly in a browser.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="go-deeper-into-the-r-ecosystem" class="slide level2">
<h2>Go deeper into the R ecosystem</h2>
<p>The R world is huge. A few doorways worth knowing:</p>
<p><strong>Modeling:</strong></p>
<ul>
<li><a href="https://www.tidymodels.org/">tidymodels</a> — predictive modeling with tidy syntax</li>
<li><a href="https://paul-buerkner.github.io/brms/">brms</a> — Bayesian regression</li>
<li><a href="https://github.com/lme4/lme4">lme4</a> — mixed-effects models</li>
</ul>
<p><strong>Text &amp; language:</strong></p>
<ul>
<li><a href="https://www.tidytextmining.com/">tidytext</a> — turn text into tidy data (you’ve seen this)</li>
<li><a href="https://ellmer.tidyverse.org/">ellmer</a> — call LLMs (Claude, GPT) from R</li>
</ul>
<aside class="notes">
<p>Don’t go deep on any of these – the point is to show that R has a thoughtful, well-built package for almost every task they’ll encounter. tidymodels is the natural next step for anyone interested in prediction or machine learning. ellmer is brand new and worth mentioning because LLM workflows are increasingly part of research.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="go-deeper-cont.-communication-workflow" class="slide level2">
<h2>Go deeper (cont.): communication &amp; workflow</h2>
<p><strong>Communication:</strong></p>
<ul>
<li><a href="https://www.danieldsjoberg.com/gtsummary/">gtsummary</a> — publication-ready summary tables</li>
<li><a href="https://quarto.org/">quarto</a> — websites, books, dashboards (you’ve used the basics)</li>
</ul>
<p><strong>Workflow:</strong></p>
<ul>
<li><a href="https://docs.ropensci.org/targets/">targets</a> — reproducible analysis pipelines</li>
<li><a href="https://rstudio.github.io/renv/">renv</a> — project-level package management</li>
</ul>
<aside class="notes">
<p>gtsummary is the single biggest time-saver for anyone writing a thesis or paper – it produces APA-style descriptives in one call. targets and renv are about making analyses survive over time: targets caches expensive computations so you don’t re-run them, and renv pins your package versions so the analysis still works two years later. Encourage them to bookmark this slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="learning-resources" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Learning resources</h1>

</section>
<section id="free-online-resources" class="slide level2">
<h2>Free online resources</h2>
<p><strong>Books:</strong></p>
<ul>
<li><a href="https://r4ds.hadley.nz/">R for Data Science (2e)</a> — your textbook</li>
<li><a href="https://learningstatisticswithr.com/">Learning Statistics with R</a></li>
<li><a href="https://adv-r.hadley.nz/">Advanced R</a></li>
<li><a href="https://ggplot2-book.org/">ggplot2: Elegant Graphics for Data Analysis</a></li>
</ul>
<div class="fragment">
<p><strong>Interactive learning:</strong></p>
<ul>
<li><a href="https://posit.cloud/learn/primers">Posit Primers</a></li>
<li><a href="https://r-bootcamp.netlify.app/">R-Bootcamp</a></li>
<li><a href="https://swirlstats.com/">swirl</a> — learn R in R</li>
</ul>
</div>
</section>
<section id="community-resources" class="slide level2">
<h2>Community resources</h2>
<p><strong>Weekly challenges:</strong></p>
<ul>
<li><a href="https://github.com/rfordatascience/tidytuesday">#TidyTuesday</a> — practice data viz</li>
<li><a href="https://adventofcode.com/">Advent of Code</a> — programming puzzles</li>
</ul>
<div class="fragment">
<p><strong>Communities:</strong></p>
<ul>
<li><a href="https://rladies.org/">R-Ladies</a> — inclusive R community</li>
<li><a href="https://r4ds.io/join">R for Data Science Slack</a></li>
<li><a href="https://community.rstudio.com/">Posit Community</a></li>
<li>Local R user groups (search Meetup.com)</li>
</ul>
</div>
</section>
<section id="keep-practicing" class="slide level2">
<h2>Keep practicing</h2>
<p><strong>The only way to maintain skills: use them</strong></p>
<div class="fragment">
<p>Ideas:</p>
<ul>
<li>Analyze data from your own research</li>
<li>Replicate figures from published papers</li>
<li>Join #TidyTuesday</li>
<li>Help friends/labmates with their data</li>
<li>Create a personal website with Quarto</li>
<li>Build a data visualization portfolio</li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Aim for 1 hour per week — consistency matters more than intensity</p>
</div>
</div>
</div>
<aside class="notes">
<p>The “1 hour per week” tip is the most actionable takeaway from this section. Skills decay fast without practice, but even a small amount of regular use keeps them sharp. TidyTuesday is the best recommendation for students who want structure – it provides a new dataset every week with a community sharing their visualizations. Encourage students to pick one or two ideas from this list, not all of them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="final-reflections" class="title-slide slide level1 center" data-background-color="#2c3e50">
<h1>Final reflections</h1>

</section>
<section id="what-makes-a-good-data-scientist" class="slide level2">
<h2>What makes a good data scientist?</h2>
<p>It’s not about knowing every function or memorizing syntax.</p>
<div class="fragment">
<p><strong>Good data scientists:</strong></p>
<ol type="1">
<li><strong>Ask good questions</strong> — what story is the data telling?</li>
<li><strong>Stay curious</strong> — always learning new tools and techniques</li>
<li><strong>Communicate clearly</strong> — make complex findings accessible</li>
<li><strong>Work reproducibly</strong> — others can verify and build on your work</li>
<li><strong>Think critically</strong> — question assumptions, check for bias</li>
<li><strong>Persist through errors</strong> — debugging is part of the job</li>
</ol>
</div>
<div class="fragment">
<p>You’ve developed all of these skills this quarter.</p>
<aside class="notes">
<p>This is the emotional core of the closing section. Slow down here. Read through the six qualities and pause on each one. The last line – “You’ve developed all of these skills this quarter” – should land. Students often don’t realize how much they’ve grown because it happened gradually. Connecting each quality back to specific class moments makes it concrete: “Remember when you debugged your partner’s code? That’s persistence.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-growth-mindset" class="slide level2">
<h2>The growth mindset</h2>
<p>Ten weeks ago, many of you had never written a line of code.</p>
<div class="fragment">
<p>Now you can:</p>
<ul>
<li>Import and clean messy data</li>
<li>Create publication-quality visualizations</li>
<li>Wrangle complex datasets with joins and pivots</li>
<li>Handle missing data appropriately</li>
<li>Build reproducible reports</li>
</ul>
</div>
<div class="fragment">
<p><strong>That’s incredible growth.</strong></p>
<aside class="notes">
<p>Let the bullet list build slowly. Each skill maps to a specific part of the course. Students may not feel like they “mastered” everything, and that’s fine – emphasize that they can do all of these things, even if they still need to look things up. Looking things up is what professionals do too. The phrase “That’s incredible growth” is genuine – let it land before moving on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="errors-are-part-of-the-process" class="slide level2">
<h2>Errors are part of the process</h2>
<p>Remember:</p>
<ul>
<li>Everyone gets errors — even experienced programmers</li>
<li>Errors mean you’re learning</li>
<li>Each error you solve makes you better</li>
<li>The frustration is temporary; the skills are permanent</li>
</ul>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>If you take one thing from this course: <strong>You can learn hard things.</strong></p>
</div>
</div>
</div>
<aside class="notes">
<p>This is the single most important message of the course. Many students came in believing they “aren’t math people” or “can’t code.” They now have evidence that they can. The callout box should be the emotional peak of the session. Pause after it. Let the room be quiet for a moment.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="thank-you" class="slide level2" data-background-color="#2c3e50">
<h2>Thank you</h2>
<p><strong>Thank you for:</strong></p>
<ul>
<li>Showing up and participating</li>
<li>Helping each other</li>
<li>Asking questions</li>
<li>Persisting through challenges</li>
<li>Trusting the process</li>
</ul>
<div class="fragment">
<p>You’ve been a great class. I’m excited to see what you do with these skills. 🎉</p>

</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>PSY 410 | Session 18</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="18-putting-it-together_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="18-putting-it-together_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="18-putting-it-together_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="18-putting-it-together_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script src="toc-nav.js"></script>
    

</body></html>